# Site
locale: 'ko-KR'
name: "haebin"
title: "haebin bolg"
description: "haebin Blog's."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url: 'http://leehaebin.github.io'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
# asd